version: "3.8"
services:
  client:
    image: react-img-comp
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-doo
    volumes:
      - ./app:/app
      # - node_modules:/app/node_modules/
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true

# volumes:
#   node_modules: